# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1479221989695");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1479225589695");
user_pref("browser.search.countryCode", "CA");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160921204512");
user_pref("browser.slowStartup.averageTime", 6745);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160921204512");
user_pref("browser.startup.homepage_override.mstone", "45.4.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1479308378055");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1479222049433");
user_pref("datareporting.policy.firstRunTime", "1479221978054");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 14570);
user_pref("datareporting.sessions.current.main", 39);
user_pref("datareporting.sessions.current.sessionRestored", 6189);
user_pref("datareporting.sessions.current.startTime", "1479222053486");
user_pref("datareporting.sessions.current.totalTime", 28);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1479221976174,\"a\":9,\"t\":56,\"c\":true,\"m\":121,\"fp\":8356,\"sr\":8106}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1479222033104,\"a\":0,\"t\":19,\"c\":true,\"m\":39,\"fp\":8570,\"sr\":6364}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7Bb555d844-5fad-45ed-a411-2535687f48a0%7D:2016.4.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.4.0");
user_pref("extensions.lastPlatformVersion", "45.4.0");
user_pref("extensions.mfull.AppInfoVersion", "45.4.0");
user_pref("extensions.mfull.config.firstrun", false);
user_pref("extensions.mfull.config.islatestoptions", true);
user_pref("extensions.mfull.config.unconfigured", false);
user_pref("extensions.mfull.installedVersion", "2016.4.0");
user_pref("extensions.mfull.show.showallbars", false);
user_pref("extensions.mfull.startup.fullscreen", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/m%20full%20screen");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{b555d844-5fad-45ed-a411-2535687f48a0}\":{\"d\":\"/home/pi/.mozilla/firefox/egc7trup.default/extensions/{b555d844-5fad-45ed-a411-2535687f48a0}.xpi\",\"e\":true,\"v\":\"2016.4.0\",\"st\":1479222034000}},\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1474604297000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474604294000}}}");
user_pref("gecko.buildID", "20160921204512");
user_pref("gecko.mstone", "45.4.0");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 24263);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1479222053);
user_pref("toolkit.telemetry.previousBuildID", "20160921204512");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
